#' @title Plot threshold vs. performance(s) for 2-class classification using ggplot2.
#'
#' @description
#' Plots threshold vs. performance(s) data that has been generated with generateThreshVsPerfData.
#'
#'
#' @param performanceByThreshold object (data.table) generated by generateThreshVsPerfData.
#' @export
#' @examples
#' 1
plotThreshVsPerf = function(performanceByThreshold) {
  dataForPlot = reshape2::melt(performanceByThreshold, id.vars = "threshold")
  colnames(dataForPlot)[-1] = c("measure", "performance")
  plt = ggplot2::ggplot(dataForPlot, aes_string(x = "threshold", y = "performance"))
  plt = plt + geom_line() + facet_wrap(~measure, scales = "free_y")
  return(plotWithTheme(plt))
}
